const TYPES={
    IAuthController:Symbol.for("IAuthController"),
    IAuthService:Symbol.for("IAuthService"),
    IUserRepository:Symbol.for("IUserRepository"),
    IRefreshRepository:Symbol.for("IRefreshRepository"),
    IFoodieRepository:Symbol.for("IFoodieRepository"),
    IFoodieService:Symbol.for("IFoodieService"),
    IFoodieController:Symbol.for("IFoodieController"),
    IAdminService:Symbol.for("IAdminService"),
    IAdminController:Symbol.for("IAdminController"),
    IRecipeRepository:Symbol.for("IRecipeRepository"),
    IRecipeService:Symbol.for("IRecipeService"),
    IRecipeController:Symbol.for("IRecipeController"),
    IReviewRepository:Symbol.for("IReviewRepository"),
    IReviewService:Symbol.for("IReviewService"),
    IReviewController:Symbol.for("IReviewController"),
    IBlogRepository:Symbol.for("IBlogRepository"),
    IBlogService:Symbol.for("IBlogService"),
    IBlogController:Symbol.for("IBlogController"),
    IChefRepository:Symbol.for("IChefRepository"),
    IChefService:Symbol.for("IChefService"),
    IChefController:Symbol.for("IChefController"),
}

export default TYPES;